### ISSUE TITLE
Dynamic Fee

### ISSUE THREAD

**Issue by luigi1111** [mymonero/mymonero-app-js#102]
MyMonero uses hard-coded fees and thus is incapable of handling dynamic fees scaling with block size increases. This also causes MM txes to stick out.

A new API call to pull and use the current dynamic fee should fix this.

**Comment by moneroexamples** [comment]
not sure if this helps, by dynamic fees for both mainnet and testnet are supported in open monero. so maybe this can help you guys do it:

https://github.com/moneroexamples/openmonero

**Comment by paulshapiro** [comment]
@moneroexamples Thank you! I have sent this to Lee.

**Comment by moneroexamples** [comment]
@paulshapiro  No problem. Hope it will helps.

**Comment by vtnerd** [comment]
@moneroexamples looks like you added a top-level field to `get_unspent_outs` called `per_kb_fee` - is that correct? My thought when I saw this ticket was similar (i.e. no additional RPC call from frontend client).

**Comment by moneroexamples** [comment]
Yes. In the backend it is here:

https://github.com/moneroexamples/openmonero/blob/master/src/YourMoneroRequests.cpp#L586

send_coins.js obviously were also modified to reflect this. 

https://github.com/moneroexamples/openmonero/blob/master/html/js/controllers/send_coins.js#L313

In fact send_coins.js has many modifications to original mymonero's version and more are coming, e.g., tx priority selection, which is already live on development server, but not yet merged to masters.
