### ISSUE TITLE
Add "big green donate button" to supplement donation address

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-app-js#111]
Figure this can open monero://

May also consider letting ppl donate in other currencies

**Comment by rstormsf** [comment]
what is `addtn` ? Could you provide more details about this issue

**Comment by paulshapiro** [comment]
"addtn" was just my short-hand for "addition" - this issue originates from a suggestion someone gave about it being too difficult to donate and he suggested that we add a "big green button" that someone can click on. And I've actually been thinking for a little while it might interesting to tie this into the idea of having a JS pill / button that can be put right into a website which constructs a button that navigates to the target of some Funds Request, i.e. monero://DONATIONADDRESS
