### ISSUE TITLE
Is www.mymonero.com service down?

### ISSUE THREAD

**Issue by jonathancross** [mymonero/mymonero-app-js#115]
I get a forced redirect to **blocked.mymonero.com**

> The site you are visiting is NOT the real MyMonero! 
> Please make sure that in future you type mymonero.com into your address bar, and don't click on links to visit the site. 
> Note that you may also see this message when trying to access MyMonero on Tor, as impersonator sites try and use Tor to reverse-proxy to MyMonero.

**Comment by paulshapiro** [comment]
Hi jonathancross, 

I do not get that. It's possibly a CORS or Tor-usage issue. However, I am going to close this as this Issues tracker is not for web wallet support items. If you need further assistance please do not hesitate to ask in #mymonero on IRC, post/search on StackExchange, or even email Ric at support.

Best
Paul

**Comment by jonathancross** [comment]
Okay, seems my IP address is being blacklisted for some reason, probably CloudFlare.
