### ISSUE TITLE
Offer unstable/nightly apk for newbies

### ISSUE THREAD

**Issue by golere** [mymonero/mymonero-app-js#116]
I'm willing to test the app even if it's unsecure/unstable but have no idea how to compile it. Would it be possible to offer the binaries for android for download (like done here: https://github.com/monero-project/monero-core/pull/780)

Newbies could check it out easily and you'll get more feedback.

**Comment by paulshapiro** [comment]
Hi golere, yes, we are absolutely going to offer binaries for download and usage. We're just waiting on a couple things. There's also the iOS build we're going to release at the same time. It's getting *really* close.

There's no need to "compile" the binaries here for release per se but you must package them. For that, we have provided packaging commands so you can make either a dev or prod build/package for yourself with one or two easy commands. Instructions are all in the readme.

Please keep an eye out for the upcoming binaries!
