### ISSUE TITLE
Build error due to package.json missing in VersoSolutions/CordovaClipboard

### ISSUE THREAD

**Issue by stoffu** [mymonero/mymonero-app-js#144]
I tried building it and encountered an error as follows:
```
npm verb node v8.9.1
npm verb npm  v5.5.1
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: com.verso.cordova.clipboard@git+https://github.com/VersoSolutions/CordovaClipboard.git.
npm ERR! package.json npm can't find a package.json file in your current directory.
```
There's a pull request for this https://github.com/VersoSolutions/CordovaClipboard/pull/27 where a fork https://github.com/ibnclaudius/CordovaClipboard is suggested as an alternative.

**Comment by paulshapiro** [comment]
Hey @stoffu, my apologies for not having replied earlier, I'll tackle this the moment I clear off a couple last minute things. Thanks for the heads up!

**Comment by paulshapiro** [comment]
Just want to mention this particular issue is now resolved with but a new blocking issue has been uncovered #151 prompting my return to the C++ core to unblock native Android app dev (had it)
