### ISSUE TITLE
Arrows and chevrons in UI elements aren't clickable

### ISSUE THREAD

**Issue by tficharmers** [mymonero/mymonero-app-js#145]
![screen shot 2017-11-13 at 11 30 49](https://user-images.githubusercontent.com/23356013/32724146-1438a616-c868-11e7-9b36-07f460715670.PNG)
![screen shot 2017-11-13 at 11 30 12](https://user-images.githubusercontent.com/23356013/32724148-147972e0-c868-11e7-84d5-f1af160e2a9a.PNG)
The right aligned arrows and chevrons aren't clickable/selectable on Desktop (MacOS). Move the mouse over them and the previously selectable state of its parent container is lost. Also occurs on the Settings page currency dropdown arrow.

**Comment by paulshapiro** [comment]
Excellent catch. Don't know how I missed those!!
