### ISSUE TITLE
Chevrons on Requests aren't vertically centred

### ISSUE THREAD

**Issue by tficharmers** [mymonero/mymonero-app-js#146]
![screen shot 2017-11-13 at 11 43 15](https://user-images.githubusercontent.com/23356013/32724264-77b0c8ea-c868-11e7-8d0a-943c4bd26039.PNG)
Chevrons on Requests aren't vertically centred (Desktop, MacOS).

**Comment by paulshapiro** [comment]
Hey @tficharmers excellent catch, and I totally see what you mean, but this was funny enough implemented to-design per mds. (See included image.) The purpose was to align the sender (requestee contact name) with the chevron. But maybe doing so causes bigger problems than it solves? I will defer to your superior design sense. 

<img width="536" alt="screen shot 2017-11-14 at 1 16 20 pm" src="https://user-images.githubusercontent.com/438826/32796965-3d5b37da-c93e-11e7-87e7-e8205ef6ed03.png">

**Comment by paulshapiro** [comment]
Yeah I'm going to go ahead and say it's better to vertically center the chevron.

**Comment by paulshapiro** [comment]
OK so it looked slightly odd to me at first. I had to measure it the pixels before my brain apparently suddenly accepted it. But I think it'll end up being the right choice.
