### ISSUE TITLE
Add subtle disclosure arrow icon to amount fieldset ccySelectLayer

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-app-js#147]
In continuation of the merged `displayCurrency` branch feedback from @tficharmers on https://github.com/mymonero/mymonero-app-js/issues/108

**Comment by tficharmers** [comment]
Following from #145, make the arrow clickable (still broken on the Settings page 'Display currency' dropdown).

**Comment by paulshapiro** [comment]
@tficharmers phew, I missed that one, I see. Thanks.

**Comment by paulshapiro** [comment]
@tficharmers this issue's resolution has been pushed at https://github.com/mymonero/mymonero-app-js/commit/d0d1cb46635878713fd27603bd6c624eb181655a… wdyt?

**Comment by tficharmers** [comment]
Yeah great :)
