### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by mmnavarr** [mymonero/mymonero-app-js#152]
Is there a repo for the iOS version of the application? I'd like to contribute to the project if it is currently open source.

**Comment by paulshapiro** [comment]
Hi Malcom, yes, there totally is an iOS version of this app, written in Swift (quite cleanly I might add!)  and it is also open source – but just for this moment we are keeping it internal. Once we release it, we will absolutely open up the repo. It will be located at github.com/mymonero/mymonero-app-ios.

May I ask what interests you in terms of contribution? There are ~40 issues on the iOS repo and I can guess you'd probably like to go through those and check them out for something interesting, but I would also venture to guess you may have had something specific in mind when thinking about what interested you. I'm very happy to collab with you over private message… do you ever use IRC? The MyMonero contributors often like to hang out on Freenode IRC in the room #mymonero 

Thank you for your interest and your note 

–Paul
