### ISSUE TITLE
Invalid fee computing???

### ISSUE THREAD

**Issue by SergeyAnkarenko** [mymonero/mymonero-app-js#167]
It seems you forgot about priority multiplier when computing newNeededFee

https://github.com/mymonero/mymonero-core-js/blob/b4b52b63d5b2b8b25c105ddf925afb86d6414350/monero_utils/monero_sendingFunds_utils.js#L348
so it should be like
```
var newNeededFee = new JSBigInt(Math.ceil(monero_utils.estimateRctSize(usingOuts.length, mixin, 2) / 1024)).multiply(feePerKB_JSBigInt).multiply(fee_multiplier_for_priority(simple_priority))
```

**Comment by paulshapiro** [comment]
Yes, looks to me like you're right. I missed those.

**Comment by paulshapiro** [comment]
Thanks @SergeyAnkarenko
