### ISSUE TITLE
Create new contact > Add ability to use the camera to scan a QR to populate the address field

### ISSUE THREAD

**Issue by tficharmers** [mymonero/mymonero-app-js#171]
Setting up a contact for paying later isn't possible at the moment. I discovered this when I tried to create a contact (on my mymonero mobile app) of my desktop wallet account, so I could send xmr to this address at a later date from my phone. But this isn't possible at the moment.

Perhaps adding the 'Use Camera' button underneath the 'Address' field would suffice?

**Comment by paulshapiro** [comment]
Absolutely, yes.

**Comment by tficharmers** [comment]
Just tried it on the latest Testflight version. I think this works well and it isn't cluttered. However there is a similar screen where I think it should be duplicated for consistency:

Monero Requests > New Monero Request > + Create New Contact

**Comment by paulshapiro** [comment]
Fixed
