### ISSUE TITLE
Max on Send - see details for UX

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-app-js#188]
This should be a blue link that only appears to the right of the ccy selector when no amount is entered - hide it when amt present 

I'm still undecided as to whether this should trigger a sweep rather than typical tx. Sweep *may* have slightly different privacy characteristics.

**Comment by paulshapiro** [comment]
Ok so to button up the UX on this one, what should happen is when the MAX btn is pressed, an (estimated probably ok, just prefixed with "~ ") 'max' amount should be shown in the Amount input field, and the MAX button should be disabled to indicate toggle. If the form is ever cleared, or the amount currency changed, or the input to the amount field ever tapped or focused or changed, then MAX should become enabled again. Then on Send, the enabled state of the MAX button can be used as `sweeping:Bool`.
Lastly, when the per kb fee ever changes, as the est fee label is getting configured, if MAX enabled, recalculate value and hydrate amount input field.

**Comment by paulshapiro** [comment]
alert on send, "Send this wallet's entire balance?"

**Comment by paulshapiro** [comment]
maybe just say "MAX" instead of inaccurate estimate (perhaps til transfer refactored not to require get_unspent_outs in the process, so we can calculate actual value on the fly for UI ... will that pose an outdated unusedOuts situation?)

**Comment by tficharmers** [comment]
That's not unconventional. The official GUI has an 'All' button inside the amount textarea and the '(all)' is put in the field. Just need to get the labeling and appearance right for mymonero.

![screen shot 2018-05-30 at 11 25 32](https://user-images.githubusercontent.com/23356013/40715035-347cc99a-63fc-11e8-8868-648a24f4f053.PNG)
