### ISSUE TITLE
Error on Open (Mac)

### ISSUE THREAD

**Issue by theGaryLambert** [mymonero/mymonero-app-js#202]
I received the following error on opening the MyMonero application on Mac. This was after completing a transaction successfully. Also, this is my first time raising an issue on github so my apologies for any errors or breaches of etiquette.

![image](https://user-images.githubusercontent.com/39474577/40290037-c5e7a258-5c89-11e8-8044-3d9ba207cbf8.png)

**Comment by paulshapiro** [comment]
Awesome, thanks for the report.

**Comment by paulshapiro** [comment]
Probably same as https://github.com/mymonero/mymonero-core-js/issues/8

**Comment by paulshapiro** [comment]
This ought to be resolved now. Lmk if you see it again
