### ISSUE TITLE
Application Hangs on Send (Mac OS X)

### ISSUE THREAD

**Issue by theGaryLambert** [mymonero/mymonero-app-js#203]
"Sending <amount I sent> XMR... Fetching decoy outputs"
Transaction does not go through

Seen on Mac OS X

**Comment by theGaryLambert** [comment]
It’s been happening every time since the error reported in issue #202 occurred. I’ll try sending from a different wallet tonight and see if it’s happening across the board or just with a specific wallet.

**Comment by theGaryLambert** [comment]
I tried to re-create the issue again over the past two days and I couldn't. Chalk it up to user error on my part.

**Comment by paulshapiro** [comment]
Hm ok could have been some kind of combination of factors. Let me know if you see it again and I'll reopen this.. :)

**Comment by paulshapiro** [comment]
Should be resolved. Lmk if you see it again!
