### ISSUE TITLE
[Feature] ability to copy/paste seed during wallet creation

### ISSUE THREAD

**Issue by anonimal** [mymonero/mymonero-app-js#207]
An understandable security implication, but for those who wish to do a quick backup of the seed (let's say, for example, to an encrypted plaintext file, or keepassx on android) the ability to copy/paste would be beneficial.

**Comment by paulshapiro** [comment]
I mentioned to anonimal in #mymonero that I'd be ok adding this capability back if we e.g. add a switch toggle to Preferences where the user has to opt in, and probably has to agree to a warning (code to support first-time warnings exists).

**Comment by paulshapiro** [comment]
I went ahead and re-enabled text selection of the mnemonic seed on desktop so that it can be copied. (Enabling right click to show context menu would be nice but electron-context-menu seems to make that a little difficult for now). This has also been re-enabled in the iOS app.
