### ISSUE TITLE
Implement camera input for qr code on Send Funds

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-app-js#21]
This was in the v1 design as another "action button" next to "Choose File", but I de-prioritized it for MVP.

Code interface needs to be platform agnostic (see FilesystemUI / Choose File)

Obviously makes a lot of sense to implement for mobile under Cordova

How to implement camera under Electron: http://ourcodeworld.com/articles/read/134/how-to-use-the-camera-with-electron-framework-create-a-snapshot-and-save-the-image-on-the-system

**Comment by shuannelson** [comment]
[This](https://www.npmjs.com/package/cordova-plugin-qrscanner#electron-or-nwjs-usage-without-cordova-browser) like a potentially great plugin for this use-case. 

Seems to support both electron and cordova, need additional testing/doc review to confirm.

**Comment by dternyak** [comment]
I've started working on this, and I have an initial implementation done here: https://github.com/dternyak/mymonero-app-js/tree/qr_scanner_v3

Things we need before this can be merged:

1. Error handling if user says No once.
2. Error handling if user says No permanently.
3. Error handling if QR Scanning succeeds but is not a Monero URI.
4. Disallow locking when app asks for permission (see line `1615` on `SendFundsView.web.js`)
```
self.context.Cordova_disallowLockDownOnAppPause += 1 // place lock so Android app doesn't tear down UI and mess up flow
```
5. Ability to cancel scanning once it has begun.
6. Figure out if there's a better way to show the camera then the current, hacky way making the entire app transparent so the camera can be seen behind it, and then un-making it transparent.

**Comment by paulshapiro** [comment]
Implemented with https://github.com/mymonero/mymonero-app-js/blob/master/local_modules/QRScanningUI/QRScanningUI.cordova.js
