### ISSUE TITLE
Try QR code without URI

### ISSUE THREAD

**Issue by selsta** [mymonero/mymonero-app-js#210]
Some websites (Kraken) don’t have an URI prefix for their QR code.

The app could try to read if it a valid address if there is no prefix.

![screen shot 2018-06-01 at 02 25 27](https://user-images.githubusercontent.com/7697454/40814949-8ffd05b2-6543-11e8-90cc-4f71a03b8bdc.png)

**Comment by paulshapiro** [comment]
Definitely
