### ISSUE TITLE
Support for importing blackball databases

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [mymonero/mymonero-app-js#220]
Users can increase their privacy by importing a blackball database into the official CLI or GUI wallet. This will tell the wallet to avoid decoy outputs that are known to be spent in other transactions.

I have a publicly-available blackball database at [moneroblackball.com](http://moneroblackball.com). It contains .txt files available for download that include one output per line. I recommend that MyMonero support the importing of these files and ability to avoid using these blackballed outputs.

**Comment by paulshapiro** [comment]
All in all, it's not a bad idea, but I don't think this should be on the app so much as the light wallet server.

**Comment by SamsungGalaxyPlayer** [comment]
@paulshapiro the server doesn't select which outputs are selected, correct? The wallet handles this behavior, not the server.

**Comment by paulshapiro** [comment]
Hm yeah my bad, guess the client would need it..

**Comment by paulshapiro** [comment]
Note edit

**Comment by SamsungGalaxyPlayer** [comment]
@paulshapiro this is the only way I could imagine it happening indirectly:

1. The wallet software selects outputs without regards for the blackballed outputs
2. The server detects that a blackballed output is used and sends a command to the wallet to request a new set of decoys
3. Repeat until an "approved" transaction with no blackballed outputs is sent

Unfortunately **this has severe privacy downsides and is not feasible.** Most importantly, by selecting a new set of decoys, the real output would be revealed.

The server could provide a list of the blackballed outputs, but ultimately the local wallet needs to decide what to do with this list.

**Comment by paulshapiro** [comment]
So the server doesn't have enough info to filter outputs it sends to the client in get_unspent_outs?

**Comment by SamsungGalaxyPlayer** [comment]
@paulshapiro I was incorrect with lightweight wallet decoy selection.

Yes, this is a server-side situation where you can avoid sending MyMonero users blackballed outputs.
