### ISSUE TITLE
When closing the app using the app's window close 'x' button, this should also completely close the app down

### ISSUE THREAD

**Issue by tficharmers** [mymonero/mymonero-app-js#232]
When closing the app using the app's window close 'x' button, this should also completely close the app down. It is currently still accessible in the MacOS CMD + TAB shortcut view and when selected, nothing can be done with the app. You then have to manually close it via the top task menu (or CMD + Q).

**Comment by Endogen** [comment]
Isn't that normal behavior? Mac apps get only closed completely by `CMD + Q`. Closing with window controls only kind of creates a standby. Try `CMD + TAB`, then select the app and then press `OPTION` key while still holding down `CMD`  and then release `CMD` (`OPTION` still pressed) and the app should open up again?

**Comment by tficharmers** [comment]
Maybe it's normal behaviour. Some MacOS apps act differently and completely shut down when the 'red X' in the menu bar is clicked. See App Store, 1password, LedgerLive and the official Monero GUI. It's not a big deal I suppose.

**Comment by paulshapiro** [comment]
@Endogen that's my handle! :)

**Comment by paulshapiro** [comment]
@tficharmers if you close the last window in the app on MacOS then click on the dock icon again, the app will reconstruct the main window. It might be a good idea in this case to have cmd-tab do the same thing, though the behavior is not quite standard across all apps, in this case, there is one main window, so it most likely makes sense.

**Comment by Endogen** [comment]
> @Endogen that's my handle! :)

No it's not, it's mine :yum:

**Comment by Endogen** [comment]
@tficharmers please make sure to close the issue if you feel that the topic is resolved

**Comment by paulshapiro** [comment]
I'm reopening this as my reply indicated an improvement

**Comment by Endogen** [comment]
Sorry, wasn't my understanding... Re-read it, got it
