### ISSUE TITLE
1.1.1-RC: new seed entry field allows newlines but rejects any seed containing them

### ISSUE THREAD

**Issue by ndorf** [mymonero/mymonero-app-js#236]
This is a minor issue but it doesn't exist in the current production web app. Tested with the 1.1.1 browser build from [here](https://github.com/mymonero/mymonero-app-js/releases/download/v1.1.1/browser_build.zip). 

The text field for entering a seed to login is now multiline. However, any entry actually containing newlines is rejected with the error 'invalid seed.'

monero-wallet-cli's `seed` command outputs the seed words in 3 lines of text, so copy/pasting that into the new app results in the error. To successfully log in, one has to remove the newlines.

On the production web app, this doesn't happen -- the seed entry field is not multiline, and so the pasted text is automatically coerced into one line. (At least with Firefox)

**Comment by paulshapiro** [comment]
This should be fixed now.
