### ISSUE TITLE
Error fetching MyMonero updates when MacBook closed

### ISSUE THREAD

**Issue by selsta** [mymonero/mymonero-app-js#242]
I think this was reported before on IRC, I’m just creating this issue for documentation.

If my MacBook is sleeping (lid closed), I’ll get a few of these once. Not sure how to solve this, maybe disable the notification.

<img width="340" alt="screenshot 2018-11-14 at 21 07 46" src="https://user-images.githubusercontent.com/7697454/48509486-8f5c8380-e851-11e8-98f0-1e0a9008aadc.png">

**Comment by paulshapiro** [comment]
Totally. One of the top things on my list for 1.1.3. Got to get through a couple core things first then ON IT. Thanks :)

**Comment by paulshapiro** [comment]
Hm oddly enough, I actually have a quick fix for this in place since Oct 11 (see `nonManualErrorNote_shownNTimes`). How many of these errors were you seeing pile up? It should only have allowed a max of 2 such.

**Comment by selsta** [comment]
I don’t remember if it was 2 or more. It’s just not that usual to have such notifications just because the app is open and the lid closed.

Anyway, I think this is really not that important, no need to spend too much thoughts on this issue :)

**Comment by paulshapiro** [comment]
Gotcha - let me know if it ends up getting crazy! I'll close this for now.
