### ISSUE TITLE
Monero URI auto-fill bugs

### ISSUE THREAD

**Issue by selsta** [mymonero/mymonero-app-js#243]
So I tried out the Monero URI here: https://kovri.io/contributing.html

The feature works great if the app is unlocked, but I’ve noticed two bugs with it if the app is locked.

1) App is locked: MyMonero opens and asks for a password. After entering the password, the app does not go to the send screen with the address prefilled.

2) App was unlocked on the send screen with addess filled in and is locked again: This one is harder to reproduce. Let’s say the app was unlocked on the send screen with an address filled in. The app gets locked after two minutes. Clicking on a Monero URI now skips the password screen resulting in a buggy state, see the screenshot below.

<img width="612" alt="screenshot 2018-12-06 at 09 42 01" src="https://user-images.githubusercontent.com/7697454/49572227-a87dbf00-f93b-11e8-85d7-d68b4cf30605.png">

Write me on IRC if my explanations are unclear :) I can send you a video.

**Comment by paulshapiro** [comment]
Hey thanks for the report on this

**Comment by paulshapiro** [comment]
heya @selsta  So 1 is a known issue, and I'll look at fixing it now (I solved it on iOS by holding the URI until unlock; clearing URI when they background the app). 2 … I'm unfortunately unable to repro!

**Comment by paulshapiro** [comment]
So 1 should now be fixed - look for it in 1.1.3! thanks selsta. Gonna close this til we can repro 2.

**Comment by selsta** [comment]
Sent you a video on IRC

**Comment by paulshapiro** [comment]
So selsta and I think this is fixed in 1.1.3. Closing for now
