### ISSUE TITLE
Web Wallet: Consider adding CSS word-break: normal; to the Secret Mnemonic text. Words are currently breaking.

### ISSUE THREAD

**Issue by tficharmers** [mymonero/mymonero-app-js#265]
The Secret Mnemonic text is currently breaking text. This is useful for the Address and Keys above it, but it would be better if these full words did not. Add `word-break: normal;` to fix this.

**Currently:**

![screen shot 2019-01-08 at 12 27 40](https://user-images.githubusercontent.com/23356013/50831264-31748580-1342-11e9-87c8-4c4b757f4980.PNG)

**Fix:**

![screen shot 2019-01-08 at 12 27 48](https://user-images.githubusercontent.com/23356013/50831304-4f41ea80-1342-11e9-8dc0-1c28e5149144.PNG)

**Comment by paulshapiro** [comment]
Good catch, thanks!.
