### ISSUE TITLE
Error fetching MyMonero updates

### ISSUE THREAD

**Issue by JanrikV** [mymonero/mymonero-app-js#268]
![mymonero](https://user-images.githubusercontent.com/36484650/51802983-3c8f4700-2258-11e9-9d12-dd763f6b4a5b.png)

Maybe 
https://github.com/mymonero/mymonero-app-js/releases/download/v.1.1.7/MyMonero-Setup-1.1.7.exe

should be:

https://github.com/mymonero/mymonero-app-js/releases/download/v1.1.7/MyMonero.Setup.1.1.7.exe

**Comment by JanrikV** [comment]
Now I got this error:

![mymonero-2](https://user-images.githubusercontent.com/36484650/51806886-32853c80-2288-11e9-9f9a-2d30e2bdabea.png)

**Comment by paulshapiro** [comment]
Bah. I'll fix it the other way

**Comment by paulshapiro** [comment]
@JanrikV does it behave any better now?

**Comment by JanrikV** [comment]
@paulshapiro  The same error as above.

**Comment by JanrikV** [comment]
@paulshapiro Any progress? Now I almost got my wallet done, until above error came up and a application close down.

**Comment by paulshapiro** [comment]
The same error is still happening?

**Comment by paulshapiro** [comment]
Could you help us ask the electron-builder team for help? The issue is linked above.

**Comment by paulshapiro** [comment]
Finally figured out the URL / 404 thing. Now dealing with a signing error.

**Comment by paulshapiro** [comment]
Turns out, by the way, that the 'not signed by…' error was actual progress.
