### ISSUE TITLE
Provide "Check sum" on MyMonero web page to verify downloaded application

### ISSUE THREAD

**Issue by Nokia808** [mymonero/mymonero-app-js#271]
Can you please provide "Check sum", preferably sha 512 (at least sha 256) for each platform version of your wallet? 

I did not see such "Check sum" on your download page. Make such check sum available will allow users to verify downloaded packages.

**Comment by paulshapiro** [comment]
They're available in the latest*.yml files on releases.

**Comment by Nokia808** [comment]
I did not see it. Sorry. I will check it. By the way, do you have plan to make your wallet available as flatpak on flathub ? This will be more secure.

**Comment by cvhoshall** [comment]
Howdy. None of the dl's (dmg, zip, exe, applmage) in versions 1.1.11, 1.1.12 or 1.1.13 check out or equal their respective sha512 hash values given in corresponding .yml files. Hashed online, desktop and using mac and linux. Please help & much appreciated,

**Comment by cvhoshall** [comment]
Hi. Convert the base16 sha512 output to base64 and viola :)
