### ISSUE TITLE
Where does the app stores its data?

### ISSUE THREAD

**Issue by moneroexamples** [mymonero/mymonero-app-js#273]
I keep forgetting when wallet data is stored, so I make this issue for future reference.

On linux it is in:

`~/.config/Electron` 

So just remove this folder if your data get corrupted and the wallet app hangs.

**Comment by paulshapiro** [comment]
Could just open a PR on the readme to augment my existing link to electron's documentation on the location of the user data.

**Comment by moneroexamples** [comment]
Sure, but I think the link here https://github.com/mymonero/mymonero-app-js#where-is-user-data-saved already points to the documentation about `app.getPath('userData')`, but it just does not spell-out clearly which folder it is.

**Comment by paulshapiro** [comment]
yeah thus the PR

**Comment by moneroexamples** [comment]
Ah I see. No problem, I will prepare it.
