### ISSUE TITLE
Currency is changed from fiat to XMR while sending if QR code is scanned after amount is inserted

### ISSUE THREAD

**Issue by vp1111** [mymonero/mymonero-app-js#280]
This seems to me like a major bug and I almost sent 10 XMR instead of 10 CAD to someone.

How to reproduce:

1. Wallet has to be configured to show values in a fiat currency (e.g. CAD).
2. Go to send screen, select an amount (e.g.) 10 CAD. It shows CAD because it's the default as set on Settings.
3. Click on Camera.
4. Scan a valid Monero QR Code (e.g. from CCS).
5. Screen now shows 10 XMR instead of 10 CAD.

Tested on iPhone.

**Comment by tficharmers** [comment]
This was discussed here:
https://github.com/mymonero/mymonero-app-ios/issues/78
But I forgot about it so haven't thought about it since. Will have another look tomorrow.

**Comment by paulshapiro** [comment]
I think I've got a resolution but will have to
confirm: dont change the form currency if an amount is entered unless the amount *and* currency are present on the request nor if there is no ccy on the request (the latter one should be happening but just in case there's a code quirk in existence).

**Comment by paulshapiro** [comment]
This is resolved by 

https://github.com/mymonero/mymonero-app-js/commit/d3ca0dbd05c1c1192d81a7784987d3764f62c382

and 

https://github.com/mymonero/mymonero-app-ios/commit/9f5bf233f5866745b66e34d89468d3815c842873
