### ISSUE TITLE
invalid transaction, invalid input problem

### ISSUE THREAD

**Issue by CompileMeSoflty** [mymonero/mymonero-app-js#281]
Hi!

I'm having a problem today with my wallet. I cannot send any funds. 
I get the following error: "An error occured while submitting transaction: Error: Invalid transaction: invalid input, "

I'm using the latest wallet and all the arguments are correct.
I know that the address is good and that the amount is correct. I've done transactions many times so it's not my first one. 

Please help!
Thank you!

**Comment by paulshapiro** [comment]
Was a daemon issue

**Comment by tkoucinauci** [comment]
Same error today...

**Comment by SergeyAnkarenko** [comment]
same thing

**Comment by andreufontb** [comment]
I have the same problem today. I cannot send any funds
