### ISSUE TITLE
invalid transaction, invalid inputs

### ISSUE THREAD

**Issue by ghost** [mymonero/mymonero-app-js#283]
Hello!

When trying to send monero, get "invalid input" error
![image](https://user-images.githubusercontent.com/6827668/57987280-ea349900-7a87-11e9-90c2-7657cfb697e4.png)

Thank you!

**Comment by devinpearson** [comment]
If anyone else has these issues, please contact our support desk a this is due to older outputs that need to be swept in order to send. We can assist you through this process.
