### ISSUE TITLE
error: unknown option `ff-only'

### ISSUE THREAD

**Issue by moneroexamples** [mymonero/mymonero-app-js#287]
Running `./bin/update_submodules` results in:

```
ntering 'local_modules/mymonero_libapp_js'
From https://github.com/mymonero/mymonero-libapp-js
 * branch            master     -> FETCH_HEAD
Already up to date.
error: unknown option `ff-only'
usage: git submodule--helper foreach [--quiet] [--recursive] [--] <command>

    -q, --quiet           Suppress output of entering each submodule command
    --recursive           Recurse into nested submodules

fatal: run_command returned non-zero status while recursing in the nested submodules of local_modules/mymonero_libapp_js
```
> git version 2.22.0

Removing the option seems as a solution.

**Comment by karlbuys** [comment]
Hi @moneroexamples. Sorry for the extremely late reply. 

I can confirm that the update_submodules script has stayed the same for two years, and works correctly under MacOS, Ubuntu and Windows 10.

This is most likely due to an issue with your specific version of git.
