### ISSUE TITLE
Sending transaction has been stuck at pending for 12 hours

### ISSUE THREAD

**Issue by tunghack** [mymonero/mymonero-app-js#289]
I am using MyMonero GUI 1.1.13 on Macbook pro. I have a sending transaction that has
been stuck at pending for many hours. The provided transaction id from the app is
not found on Monero block explorers. When I use the MyMonero web
wallet, I dont see this sending transaction. However, when I try to
send again on the web wallet, I get the error message "Transaction
rejected, double spending error". 
Is there a way to cancel this pending transaction?
Could anyone please help me with this?
Thanks,

**Comment by albertbzm** [comment]
> I am using MyMonero GUI 1.1.13 on Macbook pro. I have a sending transaction that has
> been stuck at pending for many hours. The provided transaction id from the app is
> not found on Monero block explorers. When I use the MyMonero web
> wallet, I dont see this sending transaction. However, when I try to
> send again on the web wallet, I get the error message "Transaction
> rejected, double spending error".
> Is there a way to cancel this pending transaction?
> Could anyone please help me with this?
> Thanks,

Did you solve this problem? I have the same problem.

**Comment by Alans0921** [comment]
Yesterday I had the same problem! What can I do now?

**Comment by albertbzm** [comment]
> Yesterday I had the same problem! What can I do now?

"Hi there,
Sorry for the late response we had an issue affecting a number of wallets that caused them to stop syncing. We have since resolved the issue and have rebroadcast the outstanding TX's" - Chat support response. And really, now everything works. Wait.

**Comment by devinpearson** [comment]
Closing this issue as it was resolved server side at the time.
