### ISSUE TITLE
MONERO NOT IMPORTED ?

### ISSUE THREAD

**Issue by atomicxmr** [mymonero/mymonero-app-js#293]
Please i need to Help for 1 Monero transaction . 

My Friend send me 5.78 XMR to  Monero Atomic Wallet but now Atomic wallet not support monero.

I have "Import" wallet to MyMonero but my monero not appear also ! 

Steps : 

-Connect to MyMonero Web Wallet
-use existing Wallet  
-use Adresse and private keys

When i have put all info A new window to say me to send 0.1 Monero to recover and import my wallet . 

I have send 0.1 XMR + add transaction ID Correctly .

after 10 minutes , Wallet Appear but there is 0 XMR ..

How can i do ?  i have all infos 

please help me please .

Regards

**Comment by paulshapiro** [comment]
Hey, could you email me at paul@mymonero.com and I'll check it out?

**Comment by paulshapiro** [comment]
Make sure to email me your address btw
