### ISSUE TITLE
Sub Adresses Support in App 

### ISSUE THREAD

**Issue by skyerjoe** [mymonero/mymonero-app-js#304]
Is an support for Sub Adresses on the Roadmap ? 

best regards

**Comment by devinpearson** [comment]
We are actively looking at supporting Sub Addresses in the future but don't have a fixed timeline on when that will be. Will keep you posted!

**Comment by skyerjoe** [comment]
ok thnx for info 

 best regards

**Comment by skyerjoe** [comment]
Any news about that ? 

regards
