### ISSUE TITLE
App won't open in Big Sur

### ISSUE THREAD

**Issue by invious** [mymonero/mymonero-app-js#307]
![image](https://user-images.githubusercontent.com/1996089/92005324-57b61880-ed11-11ea-8660-88a86a13d231.png)

**Comment by devinpearson** [comment]
We are very close to having a notarized version of the app out which will solve this issue

**Comment by devinpearson** [comment]
Will you give our new beta release a go. it's now notarized and you should no longer get this message.

https://github.com/mymonero/mymonero-app-js/releases/tag/v1.1.16-beta

**Comment by karlbuys** [comment]
Notarization has been performed on the 1.16 release
