### ISSUE TITLE
Windows Error - Error:ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by Bianca2112** [mymonero/mymonero-app-js#321]
User has been receiving this error sporadically for months, they are using the latest version, error is still occuring.
![mymonero error](https://user-images.githubusercontent.com/70632928/95719945-dc7d4600-0c70-11eb-908b-2bef60d6a65b.JPG)

**Comment by karlbuys** [comment]
What operating system?

**Comment by AncientSion** [comment]
I have the same issue. w10.

**Comment by devinpearson** [comment]
These have been suppressed
