### ISSUE TITLE
Windows Error - nblocksbehind < 0

### ISSUE THREAD

**Issue by Bianca2112** [mymonero/mymonero-app-js#322]
User has been receiving this error sporadically for months, they are using the latest version, error is still occuring.
![mymonero error 2](https://user-images.githubusercontent.com/70632928/95720042-00d92280-0c71-11eb-83ea-39467f25cda8.JPG)

**Comment by karlbuys** [comment]
For the desktop application, this pull request fixes the problem: https://github.com/mymonero/mymonero-app-js/pull/324

The issue will be resolved for the user once we build a new version of the wallet and distribute it

**Comment by karlbuys** [comment]
The nBlocksBehind error has been merged. This issue should no longer occur on MyMonero 1.16
