### ISSUE TITLE
 What is the version that I should download ?

### ISSUE THREAD

**Issue by isus182** [mymonero/mymonero-app-js#334]
Hi, the new version of mymonero is 1.1.16 beta or 1.1.16 latest version as indicated by https://github.com/mymonero/mymonero-app-js/releases

The link from the official website https://mymonero.com/ is to download the Beta and not the last release released I am confused

**Comment by devinpearson** [comment]
Hi @isus182 the correct one is v1.1.16 as per GitHub.

The site is in the process of been updated to reflect that

**Comment by isus182** [comment]
> updated
Thanks for your answer, I should update the information on the official page of Mymonero.com which says the latest version is 1.1.16 beta download that version from the official link
![Screenshot_20201017-114400](https://user-images.githubusercontent.com/73025474/96347192-17ff8200-106e-11eb-983a-3792d1819cde.jpg)

**Comment by devinpearson** [comment]
The site has been updated to show the correct version
