### ISSUE TITLE
can't login 

### ISSUE THREAD

**Issue by Cliff012** [mymonero/mymonero-app-js#348]
login with connection failed .
when i want to delete everything to relogin 
it return:
An unexpected application error occurred.

Please let us know of the following error message as it could be a bug:

code fault: _setBooted called while self.hasBooted=true

**Comment by devinpearson** [comment]
Hi @Cliff012 you should be able to login now.

I will however see if we can replicate the delete all bug on our side as it should not rely on you needing to be connected.

**Comment by Cliff012** [comment]
OK .i login now ,thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mymonero/mymonero-app-js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 下午4:20
收件人:&nbsp;"mymonero/mymonero-app-js"<mymonero-app-js@noreply.github.com&gt;;
抄送:&nbsp;"宁忠炜"<850709035@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mymonero/mymonero-app-js] can't login  (#348)





 
Hi @Cliff012 you should be able to login now.
 
I will however see if we can replicate the delete all bug on our side as it should not rely on you needing to be connected.
