### ISSUE TITLE
MyMonero abort/libapp.js error on startup - no clear consequences

### ISSUE THREAD

**Issue by gitgeetgot** [mymonero/mymonero-app-js#359]
![image](https://user-images.githubusercontent.com/78542192/106893285-3ce33800-66e5-11eb-8032-e45d7d0efb85.png)
Nothing seems to obviously go wrong after receiving this error message but can't hurt to report it.

**Comment by devinpearson** [comment]
We have suppressed these. They were being raised when they did not need to be
