### ISSUE TITLE
Xmr.to service in mymonero wallet is working or also died

### ISSUE THREAD

**Issue by isus182** [mymonero/mymonero-app-js#362]
In view of the fact that xmr.to closed its doors, the service in mymonero is not working? In any case, I recommend you take a look at the service of https://changenow.io/es I have used it and it is an excellent alternative, I think it can be implemented to the wallet

**Comment by karlbuys** [comment]
Hi Isus182

Thanks for suggesting them. We actually have added ChangeNow support in version 1.1.19. 

There is one issue with the integration that we're busy working on, which is that at present, it requires a 0.003 BTC minimum amount to exchange. We're busy working on adding additional providers and exploring other ways in which we can reduce that minimum limit.

**Comment by isus182** [comment]
Greetings, I am aware of the minimum, but I would recommend the exchange option with LTC where the minimum 0.0628

**Comment by isus182** [comment]
> Hi Isus182
> 
> Thanks for suggesting them. We actually have added ChangeNow support in version 1.1.19.
> 
> There is one issue with the integration that we're busy working on, which is that at present, it requires a 0.003 BTC minimum amount to exchange. We're busy working on adding additional providers and exploring other ways in which we can reduce that minimum limit.

Greetings, I am aware of the minimum, but I would recommend the exchange option with LTC where the minimum 0.0628

**Comment by devinpearson** [comment]
#368 covers the request for LTC exchange pair
