### ISSUE TITLE
Application Error (windows 10)

### ISSUE THREAD

**Issue by chrisgerrby** [mymonero/mymonero-app-js#365]
Please let us know of the following error message as it could be a bug:
Error: CONNECTION RESET
Error: CONNECTION RESET
at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
at SimpleURLLoaderWrapper.emit (events.js:210:5)

**Comment by devinpearson** [comment]
We have suppressed all the network error messages in the latest version. This should no longer show
