### ISSUE TITLE
Error: Unkown 503 error

### ISSUE THREAD

**Issue by RobinSchapendonk** [mymonero/mymonero-app-js#367]
When I try to create a new wallet, verify the correct words, then I get the error: Unkown 503 error.

**Comment by Technoash** [comment]
Same here
![image](https://user-images.githubusercontent.com/1586531/108839223-e6ed1a80-7628-11eb-8fb6-43b415bb318d.png)

**Comment by RobinSchapendonk** [comment]
same on my (android) phone

**Comment by RobinSchapendonk** [comment]
works now
