### ISSUE TITLE
changenow exchange for monero

### ISSUE THREAD

**Issue by isus182** [mymonero/mymonero-app-js#368]
It would be ideal to implement this exchange house in the purse implementing the change to ltc where the minimum is low more than for btc

**Comment by devinpearson** [comment]
Hi, @isus182 we are currently using ChangeNow as one of our exchange partners and will be expanding the pairs on offer in the near future.

**Comment by devinpearson** [comment]
We are in the process of adding additional pairs to the app. Expecting to to finished in June
