### ISSUE TITLE
Windows 10 Exchange Error 502

### ISSUE THREAD

**Issue by freemelee** [mymonero/mymonero-app-js#373]
![96351007-1018ff80-10b9-11eb-8f63-51fbc709e962](https://user-images.githubusercontent.com/77434899/112762394-72adea00-8fcd-11eb-93e1-e1d572475b90.png)

I've tried for about a month now to make this transaction but it fails with this error 502 message every time.

**Comment by devinpearson** [comment]
we have improved the error messages for the exchange service. If this is still effecting anyone we can reopen
