### ISSUE TITLE
Endless "scanning blockchain"

### ISSUE THREAD

**Issue by ZbigniewB** [mymonero/mymonero-app-js#384]
When I run MyMonero 1.1.21 (Linux) I get all the time "scanning blockchain" and the number of "blocks behind" is slowly growing. It doesn't seem to be willing to finish the scan process. Anything I can do to fix this?

**Comment by devinpearson** [comment]
It should resolve in the next while. We applied security patches to our databases and the scanner didn't restart correctly.  It is up now and going to the backlog
