### ISSUE TITLE
Need Spec Details of VM instances

### ISSUE THREAD

**Issue by RVivekkumar** [mymonero/mymonero-app-js#413]
Hi Team

   We have been Using the monero app js application for our application. We had been facing certain error after transaction more than 10  in our application.Is there any specification for the vm instance to be applied please provide us if there is any machine spec to be given for deployment of core js application

**Comment by devinpearson** [comment]
Hi there, the core-js code is what is bundled up with the client software. We haven't seen any minimum requirements.
