### ISSUE TITLE
Open User Data Folder Does Not Work

### ISSUE THREAD

**Issue by elibroftw** [mymonero/mymonero-app-js#414]
OS: Windows 10
Click the following does not do anything.
![image](https://user-images.githubusercontent.com/21298211/127713149-5cfb4326-9ea8-4025-90b5-af13ca385a35.png)

Also quick question, where are the wallet files stored? I see "AppData\Roaming\MyMonero" but no file containing my wallet's name.

**Comment by karlbuys** [comment]
Hi @elibroftw 

Thank you for reporting the issue. In the folder you're viewing, you will see a number of files that are of the type "MMDBDOC_V1".

You'll see a number of files of that type, that start with "Wallets__(unique ID)", "Settings__(unique ID)", "PasswordMeta__(unique ID).

@devinpearson -- Electron 9 upgrade error (shell.openItem is not a function). I'll roll a fix and submit a PR for it

**Comment by elibroftw** [comment]
Okay and last question. What's the encryption algorithm and encryption procedure for the wallet files? I'm trying to make a utility to decrypt wallet files in Python.

I known the official wallet uses chacha20 but to decrypt the binary wallet file is unintuitive.

**Comment by karlbuys** [comment]
Hi @elibroftw 

The file responsible for the encryption / decryption of the wallet objects is located in /local_modules/symmetric_string_cryptor.js

The content of the wallet files you have on disk should be a base64-encoded string.

The process the wallet follows when saving a wallet is as follows:

1. We take a JSON object with the wallet properties, and pass it to New_EncryptedBase64String__Async located on line 58 of symmetric_string_cryptor.js. The JSON object is encrypted using the password and converted to base64 by this function.
2. The encrypted message is converted to base64 on line 132. 
3. Once encrypted, that function invokes a callback on line 134.
4. We save the base64 string to disk.

For decryption, we read the string from the file, and invoke New_DecryptedString__Async on line 148 of symmetric_string_cryptor.js with the correct password. Assuming the password is correct, this returns a JSON-format wallet object 

Sorry about the issue you're experiencing. The save mechanism predates my and tekkzbadger coming onto the project. Ensuring atomic saving is one of the many things we're working towards, but it's a bit tricky with a relatively small development team.

If you have additional questions or there's anything I could shed light on, please don't hesitate to ask.

If you do manage to come right, we would really appreciate it if you could share that script with us, please, while we work on sorting out the wallet corruption issue

**Comment by elibroftw** [comment]
Okay I didn't mention this, but I don't actually have any issues at all. I was simply trying to help someone on Reddit who naively decided not to backup their seed.

I finally had some spare time and finished the script. https://gist.github.com/elibroftw/dc169add51b3093f8ebf35e276ae131d

I will tell you that you should really refactor your code. I was following the decryption code and its not open source friendly. Or it's not friendly for me. For such a linear process, the implementation was done in a non-linear mangle way.
- For naming, you used `unpacked_components` and `components` for the same thing. Some other names are also convoluted instead of succinct.
- There are too many function parameters. I know I would never write many functions that take in a post function argument. I've worked with Javascript before and I rarely do this nested function jungle, but I see it all the time in code. It's just my opinion but if you think it works, so be it, not my code base. 
- And too many multi-nested functions: I would've at least used actual exceptions to error handle instead of this multi nested functions passed along as parameters

**Comment by devinpearson** [comment]
@elibroftw Thanks for your feedback.

We are in the process of refactoring the apps heavily. The code is definitely not coded in a friendly and we are going through the same process you had of demangling it. 

Currently, we are rewriting the underlying Wallet class and how it interacts with the Monero Client and the MyMonero web service. The new classes are far cleaner and much more readable with exception handling and mocha tests.

I will be adding it to the public repos once it's in a usable state and would welcome public comment on the changes.

Open source projects should make it as easy as possible for community members to get it running and clear enough for them to make meaningful contributions in a short period of time. The current codebase does not live up to that ideology and we are working to change that.

**Comment by karlbuys** [comment]
Closing since #415 fixed the issue specified in the title
