### ISSUE TITLE
Found a vulnerability. How do I report it securely and privately?

### ISSUE THREAD

**Issue by wyv3rnnn** [mymonero/mymonero-app-js#417]
Hey Staff,

I'm an ethical hacker and noticed that while looking through the app on my free time that I found a critical vulnerability for the desktop app of this wallet. Is there a way to report this more securely instead of on a public issue on GitHub like this current one??? I don't want to say anything involving the vulnerability on here because people might be able to easily find it and cause problems for you guys. 

Thanks & Regards,
WYV3RN

**Comment by devinpearson** [comment]
You can send it on to support@mymonero.com

**Comment by wyv3rnnn** [comment]
Thanks!
