### ISSUE TITLE
App shows ReferenceError: shouldShow_importTxsBtn

### ISSUE THREAD

**Issue by windows11sucks** [mymonero/mymonero-app-js#432]
### App shows ReferenceError: shouldShow_importTxsBtn

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. I think it's just me so yeah
3. Wait a bit for it to popup
**Expected behavior:**

I expected it to not popup

**Actual behavior:**

It poped up

**Link to an example: [optional]**

### Versions

- Mark Text version:
- Operating system: Windows 10
![error](https://user-images.githubusercontent.com/94387154/141822143-cb68d074-3746-4c2b-9cc9-eea5c1b9ccd2.PNG)

**Comment by karlbuys** [comment]
Thank you for submitting this issue.

#433 should fix this. We'll be releasing a new version with the fix shortly.

**Comment by devinpearson** [comment]
Closing this issue. Was resolved in #433
