### ISSUE TITLE
Cannot Create Wallet

### ISSUE THREAD

**Issue by BGarber42** [mymonero/mymonero-app-js#478]
### Description

Cannot Create new wallet

- [X] Can you reproduce the issue? 

### Steps to reproduce

1. Try to create wallet
2. Get to password/pin entry

**Expected behavior:**

It works

**Actual behavior:**

![image](https://user-images.githubusercontent.com/16881353/162805303-b8dffb9f-de65-4b0d-baec-ae5b9fd12bb9.png)

**Link to an example: [optional]**

### Versions

- Mark Text version: 1.2.6
- Operating system:

**Comment by devinpearson** [comment]
Just released a new version to patch this bug. v1.2.7 should allow you to create a wallet now.

**Comment by ken0225** [comment]
yes...i have the same problem like this..

**Comment by devinpearson** [comment]
Please check that you are on the latest version. https://github.com/mymonero/mymonero-app-js/releases/tag/v1.2.7

The issue was introduced in v1.2.6 and corrected in v1.2.7
