### ISSUE TITLE
Possible to run more than 1 Instance ? 

### ISSUE THREAD

**Issue by skyerjoe** [mymonero/mymonero-app-js#504]
I want to manage more than one wallet at the same time 

So is it possible to run more than one wallet instance at the same time ?

best regards

**Comment by LivBoss** [comment]
You can definitely run multiple wallets at once within the MyMonero app. Each wallet will have its own unique address, mnemonic seed and private wallet keys. You are able to name your wallets and change the color so that you can easily differentiate between them.
