### ISSUE TITLE
MyMonero Has Hard Forked!

### ISSUE THREAD

**Issue by LivBoss** [mymonero/mymonero-app-js#513]
An update from the official MyMonero support team:

The hard fork update has taken longer than predicted.

Our engineers have worked hard and have made great progress over the past week.
This means that our wallets are now scanning to their current block height, so you are able to view your XMR within the MyMonero wallet.

We are happy to announce that tomorrow our users will be able to use the spend key function.

We will post more updates once this function is live.

If you have any questions or concerns, please feel free to reach out to us on support@mymonero.com or via our chat feature on mymonero.com.

**Comment by LivBoss** [comment]
Please see MyMonero's official response here:
[
](https://www.reddit.com/r/MyMonero/comments/wxbdb9/mymonero_important_announcement/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

**Comment by LivBoss** [comment]
https://www.reddit.com/r/MyMonero/comments/wxbdb9/mymonero_important_announcement/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by oozone** [comment]
You need to fix this now, like NOW.

**Comment by LivBoss** [comment]
Another update from the MyMonero team:

We are happy to report that our Android app has now been successfully patched and is operational again.
This now means that our Web-Wallet, Mac, Linux and Android systems are all up and running.

Our engineers are currently in the final stages of patching the mobile app for our iOS users, and the Windows systems too.
We are hopeful that these will be ready to release soon!

**Comment by LivBoss** [comment]
Just an update for all the #MyMonero users..

Our engineers are still busy working on the iOS mobile and Windows systems.

But don’t forget that you can use any of our other platforms in the meantime.

For full access to your wallet, find our web-wallet here: wallet.mymonero.com

**Comment by LivBoss** [comment]
We are happy to announce that the MyMonero wallet is fully operational once again!
We have successfully upgraded our software to fall in line with the Monero hard fork.

This good news is relevant to our web-wallet, MacOS, Linux users, as well as Android and iOS mobile app users.

Once you have updated to the latest software, you will be able to see your balances and transactions and you can now send XMR.

A note to our Windows users, we have completed the hard fork patch on the Windows software and are eager to release, we are currently awaiting a certificate that will allow us to release the software publicly.

Thank you for your patience!
