### ISSUE TITLE
Wrong balance is showing and not able to spend the mining account 

### ISSUE THREAD

**Issue by TechGoku** [mymonero/mymonero-app-js#532]
### Question description

I have created a account my-monero and i have started to use wallet for mining . i have noticed that my balance in cli wallet and mymonero is different and not able to spend the amount . from unspent outs . outputs is 0 .is mining accounts not suppoted in my monero ?

**Comment by karlbuys** [comment]
What version of MyMonero are you using?

Are you using a mining pool? You may be seeing your rewards, but they haven't been sent to your MyMonero wallet yet

**Comment by TechGoku** [comment]
I have used Private stagenet for this testing purpose . i have used both desktop wallet and web wallet .for this scenario . These mining rewards are usable in cli-wallet but in my-monero  . unless i have done a sweep all tx in cli . i am usinng the latest version of both desktop and web . i can see the mining tx outputs are not present in the unspent outs . @karlbuys  @vtnerd

**Comment by karlbuys** [comment]
MyMonero only scans mainnet, so testing stagenet functionality won't display in MyMonero. I'm afraid you won't be able to use it for stagenet testing

**Comment by TechGoku** [comment]
@karlbuys i am running my own backend from monero lws and i have changed mymonero to stagenet and running in current hardfork . which will basically mimic main-net.

**Comment by karlbuys** [comment]
@TechGoku would you be able to clarify where you changed mymonero to stagenet? Is it in an .env file in the project?

If you don't mind compiling from source, I'm happy to look into this further to see what we can do to get it working for you

If so, could you please share with me where you changed the values please? Changing just the variables likely won't address the problem. The source would need to be recompiled after changing them. Happy to talk you through it

**Comment by TechGoku** [comment]
@karlbuys I have changed in the .env file for web js. yes and i have rebuild the code before starting . i have also tested these senario with private test net . 
changes done : .env defaults file i have changed 
1. NETTYPE : 1 (while running private testnet)
2.SERVER_URL : To my local monero_lws from vtnerd .
