### ISSUE TITLE
Since 12h monero is pending after 252 confirmations

### ISSUE THREAD

**Issue by Game0verZeus** [mymonero/mymonero-app-js#542]
### Question description
I have recently sent a Monero transaction to my MyMonero wallet and have received 252 confirmations on the blockchain. However, my wallet still shows the balance as "0.6543345 pending : 0.0.6543345 locked." I am concerned about the delay in reflecting the transaction in my wallet. Is there a known issue or possible explanation for this discrepancy? Any assistance or insights would be greatly appreciated.

TRANSACTION ID : 5c72bdcb1b6eaaefbb40b3010494cf6deb253c4248982628cf89ba5924c5999b

IT always says " Your monero is on its way" since yesterday's evening

**Comment by karlbuys** [comment]
Our support team should be able to sort this out for you in the fastest way possible. I'd suggest getting in touch with them via the chat icon on the bottom right of [https://mymonero.com/](https://mymonero.com/)

They have access to specific tools that can assist you. I'll ask them to keep a look out for your problem

**Comment by Game0verZeus** [comment]
done, thanks

**Comment by karlbuys** [comment]
Hi, I'm closing this as solved. If you continue to have issues, please feel free to re-open this
