### ISSUE TITLE
Scanning blockchain without progress

### ISSUE THREAD

**Issue by slappy82** [mymonero/mymonero-app-js#543]
My desktop wallet is currently trying to scan the blockchain, but no progress is being made after several hours (it has gone from a height of around 6970 when I opened my wallet to 7026 now) and as a result the wallet is not acknowledging a recent transfer I have made. The transfer has been confirmed 81 times at the last check, and I have confirmed the address was correct.

Is there a current issue with network congestion due to all the previously inactive accounts trying to sync with the blockchain? (I believe this was the reason for this issue previously)

Using Windows 11 and MyMonero version 1.3.3

**Comment by karlbuys** [comment]
Hi

What should resolve your problem is as follows: 

1. BACK UP YOUR KEYS FIRST 
2. Delete the wallet that isn't scanning properly from the MyMonero app
3. Re-add the wallet using your mnemonic / keys

This should resolve your issue. Please re-open this ticket if it doesn't
