### ISSUE TITLE
9 confirmations and pending status in mymonero wallet

### ISSUE THREAD

**Issue by d4op** [mymonero/mymonero-app-js#544]
9 confirmations and pending status in mymonero wallet

how much confirmations are needed to be arrived status lol

**Comment by ari-party** [comment]
[Transactions show pending until unlocked](https://github.com/mymonero/mymonero-app-js/blob/5c7455d30e4e20150962f5f74efd83477962a05e/local_modules/Wallets/Views/WalletDetailsView.web.js#L928)
