### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BreakfastBeaver** [mymonero/mymonero-app-js#556]
### Description

Got this error and it said it could be a bug. 

An unexpected application error occurred. The following error message was encountered: 

 Instance of [object PromiseRejectionEvent] error - Unexpected error encountered -- Non-browser-compliance error - we received an object other than a PromiseRejectionEvent: [object PromiseRejectionEvent]
      <p>File: null <br>Line: null <br>Col: null <br>Message:
      <span style='font-size: 11px;'>Instance of [object PromiseRejectionEvent] error - Unexpected error encountered -- Non-browser-compliance error - we received an object other than a PromiseRejectionEvent: [object PromiseRejectionEvent]</span></p>
    

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text version:
- Operating system:

**Comment by BreakfastBeaver** [comment]
Not sure if I can reproduce the error it just happened once so far

**Comment by karlbuys** [comment]
Hi @BreakfastBeaver 

It could be that you lost network signal at that stage. Thank you for letting us know about it
