### ISSUE TITLE
Switch to 25-word mnemonic seed generator; support loading "old" 13-word derivation

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-app-js#77]
We need to switch to the Monero-compatible 25-word derivation, but we still need to support loading a wallet with the "old" (current) 13-word derivation.

* bear in mind that it's not just the number of words, but the derivation itself

* with Monero the mnemonic seed *is* the spend key, and the view key is a hash of the  spend key

* with MyMonero the spend key is a hash of the mnemonic seed, and then the view key is a hash of the spend key (so a double hash of the seed)

* the 25-word derivation already exists in the code, because you can import a 25-word seed

**Comment by moneroexamples** [comment]
Open monero uses 25 word seed fully comparability with monero command line wallet. It can also use 13 word seeds off course, and also supports testnet wallets. So maybe looking at how open monero does this, can help you guys:

- https://github.com/moneroexamples/openmonero

**Comment by paulshapiro** [comment]
Hi @moneroexamples,

This issue in reference to the client-side JS reimplementation for parsing and generating mnemonics rather than serverside support, as far as i know. But thanks!

Paul

**Comment by moneroexamples** [comment]
in open monero, the address and seeeds are all done in JS, on client side. mymonero's js libraries were modified for this purposes. nothing is done on the server side.

**Comment by paulshapiro** [comment]
I figure I must have misunderstood here, so I went back to your link and scanned `mnemonic.js`… but it looks to be the same as our one in mymonero-app-js. If you have a sec – would appreciate a link to where you handle 25 word mnemonics or what I should be looking at. Many thanks –Paul

**Comment by moneroexamples** [comment]
just like in mymonero, address generation from seed and seed are in cn_utils.js, login controller is login.js. In openmonero they are here:

https://github.com/moneroexamples/openmonero/tree/master/html/js

What has changed, dont remember now unfortunately, as these changes were done months ago. You would have to compare the files with what mymonero has now, or go through the github history. 

I dont know if the electron mymonero app is much different from online mymonero. I only checked if open monero's c++ backend works with the electron app last week and it worked. Didnt look into js code.

**Comment by paulshapiro** [comment]
@moneroexamples I feel a bit silly now (which must be good), as I've talked to luigi, and realized mnemonic.js only handles encoding/decoding. I see what you mean now. One change must have been in `generate_wallet.js`

```
    $scope.generateNewSeed = function () {
        //$scope.seed = cnUtil.rand_16();
        $scope.seed = cnUtil.rand_32();
    };
```

**Comment by moneroexamples** [comment]
Think so, but also have to account for 13-word seeds in address generation when someone want's to import mymonero account. This works with open monero. Usually I use meld or any diff tool to compare files between open monero and mymonero version's, to check if any changes were made in mymonero. So to see all the changes, would have to be done similar, I think.

You can also have look here: http://139.162.32.245:82 (note no ssl!) this is mainnet development version, as generation of addresses for testnet is different from mainnet.

**Comment by paulshapiro** [comment]
> also have to account for 13-word seeds in address generation when someone want's to import mymonero account

Right you are. I'll probably have a look at this tomorrow. Thanks for the prompt. :)

**Comment by paulshapiro** [comment]
Okay, looks like we're all set here. Testing and verification will be much appreciated as this is a fairly critical part.
