### ISSUE TITLE
Linux/Debian: a datastore.js toString() fail caused app to show blank screen on open

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-app-js#79]
See non-highlighted text

![ta0mpcc-1](https://cloud.githubusercontent.com/assets/438826/25624793/8cb1a40a-2f28-11e7-98c9-55c916df5356.png)

*Possibly* some undefined or unexpected object upon which document cryptor encryption is being attempted on app load. Or something Debian-specific.

**Comment by M5M400** [comment]
actually, the problem appears to be the non-highlighted text below. I still get the highlighted one after deleting the data dir, but the app comes up just fine now.

**Comment by paulshapiro** [comment]
for reference, this was probably experienced on

Ubuntu 17.04; node 4.7.2; npm 3.5.2

**Comment by paulshapiro** [comment]
Hm… not able to reproduce this issue with some basic testing under the same software versions. Anyone else seeing this?

From research, it might be caused by having a huge amount of data in the app's database… which seems very unlikely in this case (https://github.com/louischatriot/nedb/issues/389)
@M5M400 , is there any chance you had input a huge amount of wallets/requests/contacts into your app? If you happen to see this bug again, it could be great to know the size of the user data directory before you clear it.
Also, had you been using any usual data, such as any special characters? Not expecting that to be an issue but could be good to check.

**Comment by M5M400** [comment]
I didn't clear it, actually. I moved it aside for forensic purposes. Need a copy? Not much in it, though. Just imported two existing wallets. the wallets have seen a fair share of usage though from mining transactions. so the TX history is probably the biggest chunk, albeit still small.

**Comment by paulshapiro** [comment]
Okay, doesn't sound like a size limit issue. But it would be great to have that, yes. Could you send it to me privately / directly? I'll ping you on IRC.

**Comment by paulshapiro** [comment]
So taking a look at your data file, it looks like the Wallets datafile grew very large. This could possibly have been caused by the MyMonero app sitting open in the background for a long time. NeDB, the embedded database, continually appends changed records until the database is loaded again. Because the saved data in MyMonero is encrypted, updates in the background would likely have triggered the continuous appending of records, because NeDB does not automatically trigger a compaction of the datafile -- only on database load (see https://github.com/louischatriot/nedb/issues/56). To solve this, what I think I will do is have `DocumentPersister` call `db.persistence.compactDatafile` after either (a) every write operation or (b) periodically. This should enqueue a compaction operation which waits until all pending operations are finished, and should be very quick to perform, so shouldn't affect performance.
