### ISSUE TITLE
app timeout not working consistently

### ISSUE THREAD

**Issue by M5M400** [mymonero/mymonero-app-js#80]
Ubuntu 17.04; node 4.7.2, npm 3.5.2

set app timeout to 30s and auto-locking works as expected. did some testing (added a newly created wallet) and then leave the window alone in the wallet overview... checking back half an hour later, still see the wallet overview instead of the "enter password" screen.

- restarting the app works to get the auto-lockout working again
- happens sporadically; can't make out a pattern to reproduce
- no console log output

**Comment by paulshapiro** [comment]
(for my notes) tfi_charmers reports "After you create a new wallet, the timeout doesn’t kick in"

**Comment by tficharmers** [comment]
I can confirm this on macOS 10.12.3.
