### ISSUE TITLE
UI bug: Tab bar content view appears to lose left offset

### ISSUE THREAD

**Issue by M5M400** [mymonero/mymonero-app-js#87]
toying around with current master, after a while this happened:

![peek 2017-05-04 17-42](https://cloud.githubusercontent.com/assets/22886679/25712227/6296833c-30f1-11e7-85c8-5fca8ae3c380.gif)

**Comment by paulshapiro** [comment]
Wow, nice. Never seen that. Any info about your usage prior to seeing it, so we can reproduce the issue? I'll take a look at the layout code again in case something jumps out at me.

**Comment by paulshapiro** [comment]
vertp reports same apparent issue:
"I had a wallet already setup, and when I closed and re-opened the app, it went back to normal (asked me for my password)"
"one thing is that I've had mymonero running for a few days minimized, I think when I re-opened"

![ab9lg3v](https://cloud.githubusercontent.com/assets/438826/25775906/5465b556-327e-11e7-8ea1-508188e93cd2.png)

**Comment by vertp** [comment]
I experienced a similar issue. It shows up on the "enter password" view as well. 
<img width="501" alt="screen shot 2017-05-06 at 3 57 00 pm" src="https://cloud.githubusercontent.com/assets/28492967/25775926/2d2209d4-3276-11e7-8219-e684d7ab5369.png">

**Comment by paulshapiro** [comment]
@M5M400 @vertp  You know what? I bet this is a regression caused by https://github.com/mymonero/mymonero-app-js/commit/f8197dcf12b96b27adc5a5336bba5aac5ff42fec
