### ISSUE TITLE
Error creating new wallet

### ISSUE THREAD

**Issue by woodser** [mymonero/mymonero-app-js#88]
Mac OSX:

1. Click confirm on password page when creating new wallet.
2. Password page disappears.  Previous page to recite the mnemonic seed is shown.  Upper right button says "Loading...".
3. Click elsewhere within application then return to wallet.
4. Created wallet says something to the effect of "Error: could not unlock wallet".
5. Clicking on that wallet prompts error "Please let us know the following message: WalletDetailsView opened while wallet failed to init or boot."

**Comment by paulshapiro** [comment]
Hi woodser! Thanks for the detailed issue report. Could you pull the latest source code and try again? It looks like we solved the login issue. 
Best
Paul

**Comment by woodser** [comment]
Yep, seems to be fixed!
