### ISSUE TITLE
Automatically determine mixin, or have libmonero select it

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-app-js#94]
Currently, 'mixin' (ring size) is hardcoded. This is a change from the web wallet which offered three choices: 3, 6, and 9.

I guessed that it would be a good idea to start using a mixin of size 9, for now, rather than sticking with a default as low as 3. (See https://github.com/mymonero/mymonero-app-js/commit/9a5c0833f26f92cf176565a31d47d7bb9b5b3ef7)

I've heard of some discussion into having libmonero/core automatically select the mixin size, so I'm creating this ticket for the future and as a space for discussion.

**Comment by devinpearson** [comment]
Mixin's have now been fixed 10 decoys and 1 real so this is no longer needed
