### ISSUE TITLE
Receive Funds completion does not send you back to Receive Funds Detail View

### ISSUE THREAD

**Issue by shuannelson** [mymonero/mymonero-app-js#95]
After successfully creating a "receive fund" item, the expected behavior (at least to me) would be to go back to the receive funds listview to see all receive funds items.

**Comment by paulshapiro** [comment]
Thanks for reporting. I'm going to ask Matt to see what his inclination is. Anyone else want to weigh in on this one?

**Comment by mds** [comment]
Can't recall what happens? Does it take you to the tx detail?

**Comment by paulshapiro** [comment]
Oh, sorry, by Completion, he means Download. Like after you save to your photo roll, he was expecting that the app would pop the Funds Request tab's navigation stack back to root (the list).

**Comment by paulshapiro** [comment]
@mds Currently it just shows an alert saying "Saved to photo roll" but stays on the Funds Request page.

**Comment by mds** [comment]
Ah, yeah I could see going to the list view with the same alert as before.

**Comment by shuannelson** [comment]
Discussed in IRC, decided the ux is not significantly better so closing.
