### ISSUE TITLE
"Clear all data" on Android doesn't do anything.

### ISSUE THREAD

**Issue by shuannelson** [mymonero/mymonero-app-js#96]
Most likely has to do with new db implementation.

**Comment by shuannelson** [comment]
May happen on desktop as well - haven't tested.

**Comment by paulshapiro** [comment]
Works on desktop. Testing Android…

**Comment by paulshapiro** [comment]
Ok so I narrowed this down to an over-zealous check in InitiateDeleteEverything which disallows delete everything if the user hasn't entered their pw yet.

**Comment by paulshapiro** [comment]
@shuannelson Good catch! Should be working now. :)
